apiVersion: v1
kind: Service
metadata:
  name: vproapp-service-{{.Release.Name}}
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
    nodePort: {{.Values.nodeport}}
  selector:
    app: vproapp
  type: NodePort


