# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
image: richardxgf/vprofileapp
imagename: vprofileapp
tag: 5
label: myapp
port: 8080
nodeport: 30888
