apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.label}}
  name: {{.Release.Name}}-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{.Values.port}}
    nodePort: {{.Values.nodeport}}
  selector:
    app: {{.Values.label}}
  type: NodePort
status:
  loadBalancer: {}
